# Generated by Django 3.2.5 on 2021-11-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('sem', models.CharField(choices=[('1st', '1'), ('2nd', '2'), ('3rd', '3'), ('4th', '4'), ('5th', '5'), ('6th', '6'), ('7th', '7'), ('8th', '8')], max_length=10)),
            ],
        ),
    ]
