# Generated by Django 3.2.5 on 2021-12-04 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='roshan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(default='first', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2021, 12, 4, 14, 24, 18, 479303, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
