# Generated by Django 3.2.5 on 2021-12-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211207_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='desc',
            field=models.CharField(default='books on mathematics', max_length=1000),
            preserve_default=False,
        ),
    ]
