# Generated by Django 3.2.5 on 2021-12-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_request',
            name='book',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='requested_book', to='core.book'),
            preserve_default=False,
        ),
    ]
